name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-track:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow dvc[all] tensorflow pillow pandas

    - name: Verify DVC setup
      run: |
        dvc status || echo "DVC already initialized"

    - name: Pull dataset from DVC remote
      run: |
        dvc pull data/train.csv.dvc data/val.csv.dvc data/test.csv.dvc


    # ðŸ§© New step: Add src to PYTHONPATH for GitHub runner
    - name: Add src to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Run model training
      run: |
        python src/train.py

    - name: Save MLflow artifacts
      if: success()
      run: |
        echo "âœ… Training completed and logged with MLflow"
